### ISSUE TITLE
Regex validation

### ISSUE THREAD

**Issue by dmz1** [formapro/JsFormValidatorBundle#24]
Hi,

I have regex validation for user's username field defined as: 

```
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 20
            - Regex: "#^[0-9a-zA-Z_\-\.]+$#"
```

And it blows up js validator. Firebug says that `TypeError: flags is null` and blames this [line](https://github.com/formapro/JsFormValidatorBundle/blob/master/Resources/public/js/fp_js_validator.js#L1607).
