### ISSUE TITLE
Validation messages with count are not parsed correctly

### ISSUE THREAD

**Issue by hanneskaeufler** [formapro/JsFormValidatorBundle#8]
If you have a validation rule like

``` yml
#config/validation.yml
Some\Entity:
   properties:
       something:
           - Length: { min: 1, max: 255 }
```

And you submit the blank form you get an error message like so;

```
This value is too short. It should have 1 character or more.|This value is too short. It should have {{ limit }} characters or more.
```
